In [4]:
import pickle

## Original Data

Below is a file description for each design/netlist (there is only one netlist for each design): 

- {idx}.bipartite.pkl: The connectivity information between cells and nets of the bipartite graph representation of a netlist. 

- {idx}.degree.pkl: The degrees information of cells and nets. 

- {idx}.eigen.10.pkl: The top-10 eigenvectors and eigenvalues. 

- {idx}.global_information.pkl: The global information of a netlist. 

- {idx}.metis_part_dict.pkl: The Metis (Karypis and Kumar, 1998) link based partition information. 

- {idx}.net_demand_capacity.pkl: The demands and capacity information of each net. 

- {idx}.net_features.pkl: The features of each net. 

- {idx}.net_hpwl.pkl: The Half-perimeter wirelength (HPWL) for each net. 

- {idx}.nn_conn.pkl: The connectivity file prepared for NetlistGNN (Yang et al., 2022). link 

- {idx}.node_features.pkl: The features of each node.

- {idx}.targets.pkl: The processed targets or labels of each cell/net to predict. 

- node_neighbors/{idx}.node_neighbor_features.pkl: The neighborhood features for each cell/node.

In [11]:
# maps the index to the design number
with open("../data/2023-03-06_data/all.idx_to_design.pkl", "rb") as f:
    dict = pickle.load(f)
dict

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 5,
 6: 5,
 7: 5,
 8: 5,
 9: 5,
 10: 10,
 11: 10,
 12: 10,
 13: 10,
 14: 10,
 15: 10,
 16: 16,
 17: 16,
 18: 16,
 19: 16,
 20: 16,
 21: 21,
 22: 21,
 23: 21,
 24: 21,
 25: 21,
 26: 21,
 27: 27,
 28: 27,
 29: 27,
 30: 27,
 31: 27,
 32: 27,
 33: 33,
 34: 33,
 35: 33,
 36: 33,
 37: 33,
 38: 33,
 39: 39,
 40: 40,
 41: 40,
 42: 40,
 43: 40,
 44: 44,
 45: 44,
 46: 44,
 47: 44,
 48: 44,
 49: 44,
 50: 50,
 51: 50,
 52: 50,
 53: 50,
 54: 50,
 55: 50,
 56: 56,
 57: 56,
 58: 56,
 59: 56,
 60: 56,
 61: 56,
 62: 62,
 63: 62,
 64: 62,
 65: 62,
 66: 62,
 67: 62,
 68: 68,
 69: 68,
 70: 68,
 71: 68,
 72: 68,
 73: 68}

In [17]:
# connectivity information between cells and nets for bipartite representation
# matching array index = connected?
# edge_dir: 0 = source? 1 = sink?
# edge_attr: no idea, maybe the degree?
with open("../data/2023-03-06_data/0.bipartite.pkl", "rb") as f:
    dict = pickle.load(f)
print(dict)
print(dict['edge_attr'][-10:])
print(dict['net_idx'][-10:])

{'instance_idx': array([478481, 478482, 478483, ..., 797724, 738342, 797725]), 'net_idx': array([     0,      0,      0, ..., 821521, 821522, 821522]), 'edge_attr': array([3, 3, 3, ..., 2, 2, 2]), 'edge_dir': array([0, 0, 0, ..., 1, 0, 1]), 'sample_name': '/data/son/Research/chips/congestion_prediction/data/RosettaStone-GraphData-2023-03-06/superblue19/6/', 'folder': '/data/son/Research/chips/congestion_prediction/data/RosettaStone-GraphData-2023-03-06/superblue1/1/', 'design': 'superblue1', 'edge_index': array([[     0,      0,      0, ..., 797724, 821522, 797725],
       [478481, 478482, 478483, ..., 821521, 738342, 821522]])}
[1 2 1 2 1 2 1 2 2 2]
[821518 821518 821519 821519 821520 821520 821521 821521 821522 821522]


In [66]:
# cell degrees
with open("../data/2023-03-06_data/0.degree.pkl", "rb") as f:
    dict = pickle.load(f)
#print(dict.keys())
len(dict['cell_degrees'])
#print(dict['net_degrees'])

797938

In [10]:
# top 10 eigen values and eigen vectors 
with open("../data/2023-03-06_data/0.eigen.10.pkl", "rb") as f:
    dict = pickle.load(f)
dict

{'evals': array([1.9982028, 1.9984511, 1.9999945, 1.9999961, 1.9999961, 1.999997 ,
        1.999999 , 1.9999994, 2.0000005, 2.0000098], dtype=float32),
 'evects': array([[ 1.73489370e-05,  1.81367905e-05, -4.42451652e-04, ...,
         -1.69613311e-04, -1.03775405e-04,  3.63318453e-04],
        [ 2.06509212e-05,  2.13837811e-05, -4.94658831e-04, ...,
         -1.89635786e-04, -1.15998235e-04,  4.06221749e-04],
        [ 2.06760851e-05,  2.14082029e-05, -4.94659995e-04, ...,
         -1.89635917e-04, -1.15999334e-04,  4.06223349e-04],
        ...,
        [-1.21696266e-05, -1.34866805e-05,  3.12872638e-04, ...,
          1.19940436e-04,  7.35051581e-05, -2.57036416e-04],
        [-1.18891930e-05, -1.27987933e-05,  3.12860706e-04, ...,
          1.19941426e-04,  7.34357745e-05, -2.56962288e-04],
        [-1.21403045e-05, -1.31762026e-05,  3.12862045e-04, ...,
          1.19949342e-04,  7.34591595e-05, -2.56991305e-04]], dtype=float32)}

In [94]:
with open("../data/2023-03-06_data/0.node_features.pkl", "rb") as f:
    dict = pickle.load(f)
print(dict.keys())
print(dict)
print(dict['instance_features'].shape)
print(dict['instance_features'])


dict_keys(['num_instances', 'num_nets', 'x_min', 'x_max', 'y_min', 'y_max', 'min_cell_width', 'max_cell_width', 'min_cell_height', 'max_cell_height', 'instance_features', 'sample_name', 'folder', 'design'])
{'num_instances': 797938, 'num_nets': 821523, 'x_min': 1920, 'x_max': 7278720, 'y_min': 3330, 'y_max': 7276050, 'min_cell_width': 1920, 'max_cell_width': 19211520, 'min_cell_height': 13320, 'max_cell_height': 20601600, 'instance_features': array([[7.77638522e-01, 2.67399267e-01, 1.32000000e+02, 3.99800100e-04,
        0.00000000e+00, 6.00000000e+00],
       [6.15699208e-01, 4.91758242e-01, 3.59000000e+02, 7.99600200e-04,
        0.00000000e+00, 6.00000000e+00],
       [5.91820580e-01, 4.78021978e-01, 1.76000000e+02, 4.99750125e-04,
        0.00000000e+00, 0.00000000e+00],
       ...,
       [7.77506596e-01, 1.34615385e-01, 6.00000000e+00, 1.59920040e-03,
        0.00000000e+00, 6.00000000e+00],
       [7.75593668e-01, 9.34065934e-02, 6.00000000e+00, 1.59920040e-03,
        0.0000000

In [89]:
with open("../data/2023-03-06_data/0.node_features.pkl", "rb") as f:
    dict = pickle.load(f)
print(dict['instance_features'][0])
print(dict['instance_features'].shape)

[7.77638522e-01 2.67399267e-01 1.32000000e+02 3.99800100e-04
 0.00000000e+00 6.00000000e+00]
(797938, 6)


In [90]:
with open("../data/2023-03-06_data/0.net_features.pkl", "rb") as f:
    dict = pickle.load(f)
print(dict.keys())
print(dict['instance_features'][0])
dict['instance_features'].shape

dict_keys(['instance_features'])
[ 9.8392700e+05  2.6645090e+02  0.0000000e+00  4.1767200e+05
  1.4504403e+05  3.1538994e+05  1.4943203e+05  3.9212781e+05
  5.4454250e+05  1.1225168e+05  2.7461322e+05  2.0919844e+05
  1.7670420e+04  5.0648119e+05  8.4914600e+05  4.0419009e+05
  1.3343519e+06  1.4035854e+06  2.6564066e+05  1.0652486e+06
  6.0974419e+05  4.1504445e+04  1.2290500e+05  2.6057900e+05
  4.7308500e+05  7.7726800e+05  1.1596730e+06  1.8579820e+06
  4.2378000e+05  7.0933500e+05  1.1935630e+06  1.8414130e+06
  2.7894380e+06  4.1105650e+06  1.9671024e+00  2.0726898e+00
 -5.3799072e+01 -6.0643272e+01  1.4420410e+00 -4.4606724e+00
 -2.9280889e+00 -2.0650249e+01 -1.2616593e+01  4.4177708e+01
  1.7341040e+01  4.1642575e+00  5.9796691e-01  7.7328318e-01
  3.5756442e-01  5.6296331e-01  8.2648188e-01]


(821523, 51)

In [18]:
# cell demand, capacity, congestion
with open("../data/2023-03-06_data/0.targets.pkl", "rb") as f:
    dict = pickle.load(f)
dict

{'demand': array([ 0.        ,  0.        ,  0.        , ...,  2.5       ,
        10.83333333,  5.        ]),
 'capacity': array([21.66666667, 23.33333333, 23.33333333, ...,  3.33333333,
        25.        ,  3.33333333]),
 'classify': tensor([[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [1]])}

## New Data

In [27]:
with open("../data/Design_100_netlist_data/net2sink_nodes.pkl", "rb") as f:
    dict = pickle.load(f)
len(dict[0])

600

In [ ]:
# 661360 nodes?

In [44]:
with open("../target_data/Design_100_1000_AltSpreadLogic_high/node_loc_x.pkl", "rb") as f:
    dict = pickle.load(f)
dict

array([130., 195.,  11., ..., 138., 138.,  68.], dtype=float32)

In [39]:
with open("../target_data/Design_100_1000_AltSpreadLogic_high/pl_part_dict.pkl", "rb") as f:
    dict = pickle.load(f)
dict

{0: 1567,
 1: 2351,
 2: 100,
 3: 425,
 4: 2462,
 5: 6,
 6: 357,
 7: 1310,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 1688,
 41: 1497,
 42: 1245,
 43: 1094,
 44: 596,
 45: 2174,
 46: 2174,
 47: 2174,
 48: 2174,
 49: 2174,
 50: 2174,
 51: 2174,
 52: 2174,
 53: 2174,
 54: 2124,
 55: 647,
 56: 2125,
 57: 2125,
 58: 2125,
 59: 2125,
 60: 2175,
 61: 2125,
 62: 2175,
 63: 2175,
 64: 2175,
 65: 2125,
 66: 646,
 67: 2174,
 68: 2174,
 69: 2174,
 70: 2174,
 71: 2176,
 72: 2174,
 73: 2174,
 74: 2176,
 75: 2123,
 76: 2174,
 77: 646,
 78: 2174,
 79: 2174,
 80: 2174,
 81: 2174,
 82: 2174,
 83: 2174,
 84: 2174,
 85: 2174,
 86: 2125,
 87: 2123,
 88: 546,
 89: 2224,
 90: 2224,
 91: 2224,
 92: 2224,
 93: 2224,
 94: 2174,
 95: 2224,
 96: 2178,
 97: 2178,
 98: 2124,
 99: 646,
 100: 2174,
 101: 

In [45]:
# different length? (718597)
with open("../target_data/Design_100_1000_AltSpreadLogic_high/target_net_hpwl.pkl", "rb") as f:
    d = pickle.load(f)
d

array([498. ,   6. ,  10. , ...,   2.5,   2.5,   2.5])

In [52]:
with open("../target_data/Design_100_1000_AltSpreadLogic_high/target_node_utilization.pkl", "rb") as f:
    dict = pickle.load(f)
dict

array([314., 315., 284., ..., 316., 282., 245.], dtype=float32)

In [46]:
with open("../target_data/Design_100_1000_AltSpreadLogic_high/top_pl_part_dict.pkl", "rb") as f:
    d = pickle.load(f)
d

{0: 16,
 1: 20,
 2: 0,
 3: 2,
 4: 21,
 5: 0,
 6: 0,
 7: 11,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 18,
 41: 14,
 42: 14,
 43: 14,
 44: 9,
 45: 22,
 46: 22,
 47: 22,
 48: 22,
 49: 22,
 50: 22,
 51: 22,
 52: 22,
 53: 22,
 54: 22,
 55: 9,
 56: 22,
 57: 22,
 58: 22,
 59: 22,
 60: 22,
 61: 22,
 62: 22,
 63: 22,
 64: 22,
 65: 22,
 66: 9,
 67: 22,
 68: 22,
 69: 22,
 70: 22,
 71: 22,
 72: 22,
 73: 22,
 74: 22,
 75: 22,
 76: 22,
 77: 9,
 78: 22,
 79: 22,
 80: 22,
 81: 22,
 82: 22,
 83: 22,
 84: 22,
 85: 22,
 86: 22,
 87: 22,
 88: 9,
 89: 22,
 90: 22,
 91: 22,
 92: 22,
 93: 22,
 94: 22,
 95: 22,
 96: 22,
 97: 22,
 98: 22,
 99: 9,
 100: 22,
 101: 22,
 102: 22,
 103: 22,
 104: 22,
 105: 22,
 106: 22,
 107: 22,
 108: 22,
 109: 22,
 110: 9,
 111: 22,
 112: 22,
 113: 22,
 114: 22,
 11

In [72]:
import torch
with open("../data/Design_100_netlist_data/pyg_data.pkl", "rb") as f:
    d = torch.load(f)
d

/var/folders/n3/dkf1dhtx7_z72kxwtk9dwfpr0000gn/T/ipykernel_23311/703438358.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d = torch.load(f)


Data(node_features=[661360, 21], net_features=[718597, 12], edge_index_source_sink=[2, 1703893], edge_index_sink_to_net=[2, 1703893], edge_index_source_to_net=[2, 718597])